// Code generated by protoc-gen-go.
// source: message/message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message/message.proto

It has these top-level messages:
	Header
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Type32  uint32 `protobuf:"varint,1,opt,name=type32" json:"type32,omitempty"`
	Service uint32 `protobuf:"varint,2,opt,name=service" json:"service,omitempty"`
	Flags   uint32 `protobuf:"varint,3,opt,name=flags" json:"flags,omitempty"`
	NodeID  []byte `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Body    []byte `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Id      uint32 `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetType32() uint32 {
	if m != nil {
		return m.Type32
	}
	return 0
}

func (m *Header) GetService() uint32 {
	if m != nil {
		return m.Service
	}
	return 0
}

func (m *Header) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Header) GetNodeID() []byte {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *Header) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Header) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Header)(nil), "message.Header")
}

func init() { proto.RegisterFile("message/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x52, 0x0f, 0x23, 0x17, 0x9b, 0x47, 0x6a, 0x62, 0x4a, 0x6a, 0x91, 0x90, 0x18, 0x17, 0x5b, 0x49,
	0x65, 0x41, 0xaa, 0xb1, 0x91, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x94, 0x27, 0x24, 0xc1,
	0xc5, 0x5e, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xc1, 0x04, 0x96, 0x80, 0x71, 0x85, 0x44,
	0xb8, 0x58, 0xd3, 0x72, 0x12, 0xd3, 0x8b, 0x25, 0x98, 0xc1, 0xe2, 0x10, 0x0e, 0xc8, 0x9c, 0xbc,
	0xfc, 0x94, 0x54, 0x4f, 0x17, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x28, 0x4f, 0x48, 0x88,
	0x8b, 0x25, 0x29, 0x3f, 0xa5, 0x52, 0x82, 0x0d, 0x2c, 0x0a, 0x66, 0x0b, 0xf1, 0x71, 0x31, 0x65,
	0xa6, 0x48, 0xb0, 0x83, 0xb5, 0x33, 0x65, 0xa6, 0x24, 0xb1, 0x81, 0x9d, 0x67, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x03, 0x17, 0x90, 0xd5, 0xb7, 0x00, 0x00, 0x00,
}
