// Code generated by protoc-gen-go.
// source: message/message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message/message.proto

It has these top-level messages:
	Header
	Addrpb
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Type32  uint32  `protobuf:"varint,1,opt,name=type32" json:"type32,omitempty"`
	Service uint32  `protobuf:"varint,2,opt,name=service" json:"service,omitempty"`
	Flags   uint32  `protobuf:"varint,3,opt,name=flags" json:"flags,omitempty"`
	Body    []byte  `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Id      uint32  `protobuf:"varint,5,opt,name=id" json:"id,omitempty"`
	NodeID  []byte  `protobuf:"bytes,6,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addrpb  *Addrpb `protobuf:"bytes,7,opt,name=Addrpb" json:"Addrpb,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetType32() uint32 {
	if m != nil {
		return m.Type32
	}
	return 0
}

func (m *Header) GetService() uint32 {
	if m != nil {
		return m.Service
	}
	return 0
}

func (m *Header) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Header) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Header) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Header) GetNodeID() []byte {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *Header) GetAddrpb() *Addrpb {
	if m != nil {
		return m.Addrpb
	}
	return nil
}

type Addrpb struct {
	Ip   []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Zone string `protobuf:"bytes,3,opt,name=zone" json:"zone,omitempty"`
}

func (m *Addrpb) Reset()                    { *m = Addrpb{} }
func (m *Addrpb) String() string            { return proto.CompactTextString(m) }
func (*Addrpb) ProtoMessage()               {}
func (*Addrpb) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Addrpb) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *Addrpb) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Addrpb) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func init() {
	proto.RegisterType((*Header)(nil), "message.Header")
	proto.RegisterType((*Addrpb)(nil), "message.Addrpb")
}

func init() { proto.RegisterFile("message/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xdc, 0x4d, 0x71, 0x5c, 0x15, 0x06, 0x95, 0x39, 0x96, 0xbd, 0xd8, 0xd3, 0x0a,
	0xdb, 0x17, 0x50, 0xf0, 0xa0, 0xd7, 0xbc, 0x41, 0x6b, 0xc6, 0x12, 0xd0, 0x26, 0x24, 0x45, 0xa8,
	0xef, 0xe5, 0xfb, 0x49, 0xa7, 0xe9, 0x29, 0xff, 0xf7, 0xcf, 0x4f, 0xe6, 0x67, 0xe0, 0xfe, 0x9b,
	0x73, 0xee, 0x06, 0x7e, 0x2a, 0xef, 0x29, 0xa6, 0x30, 0x05, 0xac, 0x0a, 0x1e, 0xff, 0x14, 0x98,
	0x37, 0xee, 0x1c, 0x27, 0x7c, 0x00, 0x33, 0xcd, 0x91, 0xdb, 0x33, 0xa9, 0x5a, 0x35, 0xd7, 0xb6,
	0x10, 0x12, 0x54, 0x99, 0xd3, 0x8f, 0xff, 0x60, 0xd2, 0x32, 0xd8, 0x10, 0xef, 0x60, 0xff, 0xf9,
	0xd5, 0x0d, 0x99, 0x2e, 0xc4, 0x5f, 0x01, 0x11, 0x76, 0x7d, 0x70, 0x33, 0xed, 0x6a, 0xd5, 0x1c,
	0xac, 0x68, 0xbc, 0x01, 0xed, 0x1d, 0xed, 0x25, 0xa6, 0xbd, 0x5b, 0x76, 0x8d, 0xc1, 0xf1, 0xfb,
	0x2b, 0x19, 0x49, 0x15, 0xc2, 0x47, 0x30, 0x2f, 0xce, 0xa5, 0xd8, 0x53, 0x55, 0xab, 0xe6, 0xea,
	0x7c, 0x7b, 0xda, 0x7a, 0xaf, 0xb6, 0x2d, 0xe3, 0xe3, 0xf3, 0x16, 0x94, 0xaf, 0xa3, 0x54, 0x3e,
	0x58, 0xed, 0xe3, 0xb2, 0x3e, 0x86, 0x34, 0x95, 0xae, 0xa2, 0x17, 0xef, 0x37, 0x8c, 0x2c, 0x3d,
	0x2f, 0xad, 0xe8, 0xde, 0xc8, 0x25, 0xda, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x0c, 0xfe,
	0x60, 0x22, 0x01, 0x00, 0x00,
}
